# Generated by Django 5.2.1 on 2025-06-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('gpa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpa', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_class', models.CharField(choices=[('必修', '必修'), ('教養', '教養'), ('専門', '専門')], max_length=10)),
                ('subject_score', models.IntegerField(default=1)),
                ('subject_count', models.IntegerField(default=0)),
                ('lesson_days', models.IntegerField(default=15)),
                ('attend_days', models.IntegerField(default=0)),
                ('lesson_count', models.IntegerField(default=0)),
                ('date', models.CharField(default='月曜日', max_length=10)),
                ('table', models.CharField(default='1限目', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]
