# Generated by Django 5.2.1 on 2025-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
