# Generated by Django 5.1.2 on 2025-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lesson_count',
            field=models.IntegerField(default=15),
        ),
    ]
