# Generated by Django 5.1.2 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subject_lesson_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='lesson_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
