# Generated by Django 5.1.2 on 2025-12-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subject_lesson_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
