# Generated by Django 5.1.2 on 2025-12-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lesson_days',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_count',
        ),
    ]
