# Generated by Django 5.1.2 on 2025-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_subject_lesson_days_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('student', 'subject_name'), name='unique_student_subject'),
        ),
    ]
