# Generated by Django 5.2.1 on 2026-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subject_unique_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
